import { AppShell } from "@/components/app-shell"
import { alerts } from "@/lib/data"
import {
  Sparkles,
  ShieldAlert,
  AlertTriangle,
  Info,
  ArrowUpRight,
} from "lucide-react"
import Link from "next/link"
import { cn } from "@/lib/utils"

export default function AlertsPage() {
  return (
    <AppShell title="Alerts">
      <header className="mb-6">
        <p className="text-xs text-muted-foreground inline-flex items-center gap-1.5">
          <Sparkles className="size-3 text-primary" />
          Generated by your agents
        </p>
        <h1 className="mt-1 text-2xl md:text-3xl font-semibold tracking-tight text-balance">
          Alerts that need your attention.
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          High-value matches, scam warnings, and important system events.
        </p>
      </header>

      <ul className="rounded-xl border border-border bg-card divide-y divide-border">
        {alerts.map((a) => {
          const Icon =
            a.severity === "critical"
              ? ShieldAlert
              : a.severity === "warning"
                ? AlertTriangle
                : a.type === "deal" || a.type === "match"
                  ? Sparkles
                  : Info

          const tone =
            a.severity === "critical"
              ? "bg-danger/10 text-danger"
              : a.severity === "warning"
                ? "bg-warning/10 text-warning"
                : a.type === "deal" || a.type === "match"
                  ? "bg-primary/10 text-primary"
                  : "bg-muted text-muted-foreground"

          const Content = a.listingId ? Link : "div"
          return (
            <li key={a.id}>
              <Content
                {...(a.listingId
                  ? { href: `/results/${a.listingId}` }
                  : {})}
                className={cn(
                  "flex items-start gap-4 p-4 md:p-5 transition-colors",
                  a.listingId && "hover:bg-muted/40 cursor-pointer",
                )}
              >
                <span
                  className={`size-9 rounded-lg grid place-items-center shrink-0 ${tone}`}
                >
                  <Icon className="size-4" />
                </span>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="text-sm font-semibold tracking-tight">
                      {a.title}
                    </h3>
                    <SeverityPill severity={a.severity} />
                  </div>
                  <p className="mt-1 text-sm text-muted-foreground leading-relaxed">
                    {a.description}
                  </p>
                  <div className="mt-2 flex items-center gap-3 text-[11px] text-muted-foreground">
                    <span className="font-mono">{a.timestamp}</span>
                    <span className="capitalize">{a.type}</span>
                  </div>
                </div>
                {a.listingId && (
                  <ArrowUpRight className="size-4 text-muted-foreground shrink-0 mt-1" />
                )}
              </Content>
            </li>
          )
        })}
      </ul>
    </AppShell>
  )
}

function SeverityPill({
  severity,
}: {
  severity: "info" | "warning" | "critical"
}) {
  const map = {
    info: { label: "Info", cls: "text-muted-foreground border-border bg-muted" },
    warning: {
      label: "Warning",
      cls: "text-warning border-warning/30 bg-warning/10",
    },
    critical: {
      label: "Critical",
      cls: "text-danger border-danger/30 bg-danger/10",
    },
  }
  const m = map[severity]
  return (
    <span
      className={`text-[10px] uppercase tracking-wide font-medium px-1.5 py-0.5 rounded border ${m.cls}`}
    >
      {m.label}
    </span>
  )
}
