"use client"

import { useEffect, useState } from "react"
import { AppShell } from "@/components/app-shell"
import { notifications as notifApi, type BackendNotification } from "@/lib/api"
import {
  Sparkles,
  ShieldAlert,
  AlertTriangle,
  Info,
  ArrowUpRight,
  Loader2,
  CheckCheck,
} from "lucide-react"
import Link from "next/link"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"

export default function AlertsPage() {
  const [items, setItems] = useState<BackendNotification[]>([])
  const [loading, setLoading] = useState(true)

  const load = () => {
    notifApi
      .list({ limit: 50 })
      .then(setItems)
      .catch(console.error)
      .finally(() => setLoading(false))
  }

  useEffect(() => { load() }, [])

  const markAllRead = async () => {
    await notifApi.markAllRead().catch(console.error)
    load()
  }

  const markRead = async (id: number) => {
    await notifApi.markRead(id).catch(console.error)
    setItems((prev) => prev.map((n) => n.id === id ? { ...n, is_read: true } : n))
  }

  const unreadCount = items.filter((n) => !n.is_read).length

  return (
    <AppShell title="Alerts">
      <header className="mb-6 flex items-start justify-between gap-4 flex-wrap">
        <div>
          <p className="text-xs text-muted-foreground inline-flex items-center gap-1.5">
            <Sparkles className="size-3 text-primary" />
            Generated by your agents
          </p>
          <h1 className="mt-1 text-2xl md:text-3xl font-semibold tracking-tight text-balance">
            {loading ? "Loading…" : `${items.length} alert${items.length !== 1 ? "s" : ""}${unreadCount ? ` · ${unreadCount} unread` : ""}`}
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            High-value matches, scam warnings, and important system events.
          </p>
        </div>
        {unreadCount > 0 && (
          <Button variant="outline" size="sm" className="gap-2 rounded-full" onClick={markAllRead}>
            <CheckCheck className="size-3.5" />
            Mark all read
          </Button>
        )}
      </header>

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="size-6 animate-spin text-muted-foreground" />
        </div>
      ) : items.length === 0 ? (
        <div className="text-center py-20 text-muted-foreground text-sm">No alerts yet.</div>
      ) : (
        <ul className="rounded-xl border border-border bg-card divide-y divide-border">
          {items.map((n) => {
            const isScam = n.notification_type === "scam_alert"
            const isMatch = n.notification_type === "new_match" || n.notification_type === "deal_alert"
            const isWarning = n.notification_type === "price_change"

            const Icon = isScam ? ShieldAlert : isWarning ? AlertTriangle : isMatch ? Sparkles : Info
            const tone = isScam
              ? "bg-danger/10 text-danger"
              : isWarning
                ? "bg-warning/10 text-warning"
                : isMatch
                  ? "bg-primary/10 text-primary"
                  : "bg-muted text-muted-foreground"
            const severity = isScam ? "critical" : isWarning ? "warning" : "info"

            return (
              <li
                key={n.id}
                onClick={() => !n.is_read && markRead(n.id)}
                className={cn(
                  "flex items-start gap-4 p-4 md:p-5 transition-colors cursor-pointer",
                  !n.is_read && "bg-muted/30",
                  "hover:bg-muted/40",
                )}
              >
                <span className={`size-9 rounded-lg grid place-items-center shrink-0 ${tone}`}>
                  <Icon className="size-4" />
                </span>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <h3 className="text-sm font-semibold tracking-tight">{n.title ?? "Alert"}</h3>
                    <SeverityPill severity={severity} />
                    {!n.is_read && (
                      <span className="size-1.5 rounded-full bg-primary" />
                    )}
                  </div>
                  <p className="mt-1 text-sm text-muted-foreground leading-relaxed">
                    {n.description ?? ""}
                  </p>
                  <div className="mt-2 flex items-center gap-3 text-[11px] text-muted-foreground">
                    <span className="font-mono">
                      {new Date(n.created_at).toLocaleString()}
                    </span>
                    <span className="capitalize">{n.notification_type?.replace("_", " ") ?? "info"}</span>
                  </div>
                </div>
                {n.related_listing_id && (
                  <Link href={`/results`} onClick={(e) => e.stopPropagation()}>
                    <ArrowUpRight className="size-4 text-muted-foreground shrink-0 mt-1 hover:text-foreground" />
                  </Link>
                )}
              </li>
            )
          })}
        </ul>
      )}
    </AppShell>
  )
}

function SeverityPill({ severity }: { severity: "info" | "warning" | "critical" }) {
  const map = {
    info: { label: "Info", cls: "text-muted-foreground border-border bg-muted" },
    warning: { label: "Warning", cls: "text-warning border-warning/30 bg-warning/10" },
    critical: { label: "Critical", cls: "text-danger border-danger/30 bg-danger/10" },
  }
  const m = map[severity]
  return (
    <span className={`text-[10px] uppercase tracking-wide font-medium px-1.5 py-0.5 rounded border ${m.cls}`}>
      {m.label}
    </span>
  )
}
